In [34]:
import numpy as np
import pandas as pd

In [35]:
data_frame = pd.DataFrame(np.random.rand(10,5), 
index=['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8', 'row9', 'row10'], 
columns=['col1', 'col2', 'col3', 'col4', 'col5'])

data_frame

           col1      col2      col3      col4      col5
row1   0.173619  0.810541  0.259286  0.540077  0.063031
row2   0.658666  0.778949  0.240251  0.683279  0.592408
row3   0.767643  0.394484  0.350598  0.736028  0.902721
row4   0.295006  0.815666  0.321955  0.554998  0.891741
row5   0.105757  0.516245  0.038443  0.748324  0.926711
row6   0.828665  0.560169  0.357579  0.998993  0.195791
row7   0.495857  0.111837  0.311770  0.473488  0.204135
row8   0.383201  0.376590  0.962287  0.085412  0.606867
row9   0.553638  0.148218  0.919875  0.688762  0.052952
row10  0.960867  0.780580  0.442983  0.442763  0.920745

In [36]:
data_frame.head(3)

          col1      col2      col3      col4      col5
row1  0.173619  0.810541  0.259286  0.540077  0.063031
row2  0.658666  0.778949  0.240251  0.683279  0.592408
row3  0.767643  0.394484  0.350598  0.736028  0.902721

In [37]:
data_frame.tail(2)

           col1      col2      col3      col4      col5
row9   0.553638  0.148218  0.919875  0.688762  0.052952
row10  0.960867  0.780580  0.442983  0.442763  0.920745

In [38]:
data_frame.sample(2)

          col1      col2      col3      col4      col5
row6  0.828665  0.560169  0.357579  0.998993  0.195791
row1  0.173619  0.810541  0.259286  0.540077  0.063031

In [39]:
data_frame1 = pd.DataFrame.from_dict({'A': [1,2,3], 'B': [4,5,6],'C':[7,8,9]},)
data_frame1

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [40]:
data_frame_map_label_index = pd.DataFrame.from_dict({'A': [1,2,3], 'B': [4,5,6],'C':[7,8,9]}, 
orient="index", columns=['col1', 'col2', 'col3'])

data_frame_map_label_index

   col1  col2  col3
A     1     2     3
B     4     5     6
C     7     8     9

In [41]:
df_movies = pd.read_csv('Datasets/imdb_top_1000.csv')
df_movies.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [42]:
df_movies['Released_Year']

0      1994
1      1972
2      2008
3      1974
4      1957
       ...
995    1961
996    1956
997    1953
998    1944
999    1935
Name: Released_Year, Length: 1000, dtype: str

In [43]:
# Fancy Indexing
df_movies[['Released_Year','Series_Title']]

    Released_Year              Series_Title
0            1994  The Shawshank Redemption
1            1972             The Godfather
2            2008           The Dark Knight
3            1974    The Godfather: Part II
4            1957              12 Angry Men
..            ...                       ...
995          1961    Breakfast at Tiffany's
996          1956                     Giant
997          1953     From Here to Eternity
998          1944                  Lifeboat
999          1935              The 39 Steps

[1000 rows x 2 columns]

In [44]:
# Checking the Metatype
print(type(df_movies[['Released_Year','Poster_Link']]))

<class 'pandas.DataFrame'>

In [45]:
df_movies[['Series_Title', 'Released_Year']].head()

               Series_Title Released_Year
0  The Shawshank Redemption          1994
1             The Godfather          1972
2           The Dark Knight          2008
3    The Godfather: Part II          1974
4              12 Angry Men          1957

In [46]:
df_movies.loc[0:5]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"

In [47]:
# This performs indexing in columns only
df_movies.loc[::, 'Series_Title':'Released_Year']

                 Series_Title Released_Year
0    The Shawshank Redemption          1994
1               The Godfather          1972
2             The Dark Knight          2008
3      The Godfather: Part II          1974
4                12 Angry Men          1957
..                        ...           ...
995    Breakfast at Tiffany's          1961
996                     Giant          1956
997     From Here to Eternity          1953
998                  Lifeboat          1944
999              The 39 Steps          1935

[1000 rows x 2 columns]

In [48]:
df_movies.iloc[0:5,0:3]

,Poster_Link,Series_Title,Released_Year
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957

In [49]:
df_movies.loc[0:5, 'Series_Title':'Released_Year'] = "Pakistan"
df_movies.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,Pakistan,Pakistan,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,Pakistan,Pakistan,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,Pakistan,Pakistan,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,Pakistan,Pakistan,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,Pakistan,Pakistan,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [50]:
df_movies['Recomended'] = df_movies['IMDB_Rating'] > 8
df_movies.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Recomended
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,Pakistan,Pakistan,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",True
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,Pakistan,Pakistan,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",True
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,Pakistan,Pakistan,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444",True
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,Pakistan,Pakistan,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",True
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,Pakistan,Pakistan,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",True

In [51]:
import numpy as np
import pandas as pd

In [53]:
df = pd.DataFrame(np.random.rand(5,5), columns=['Col1', 'col2', 'col3', 'col4', 'col5'], index=['row1', 'row2', 'row3', 'row4', 'row5'])
df

          Col1      col2      col3      col4      col5
row1  0.913932  0.537489  0.931904  0.789395  0.663030
row2  0.784190  0.841826  0.812536  0.296855  0.378448
row3  0.945657  0.576746  0.686857  0.571304  0.784633
row4  0.045757  0.716486  0.266165  0.120800  0.018412
row5  0.411130  0.988097  0.265319  0.576036  0.009440

In [54]:
df.head(2)

          Col1      col2      col3      col4      col5
row1  0.913932  0.537489  0.931904  0.789395  0.663030
row2  0.784190  0.841826  0.812536  0.296855  0.378448

In [56]:
df_from_dict = pd.DataFrame.from_dict({'A': [1,2,3], 'B': [4,5,6],'C':[7,8,9]})
df_from_dict

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

Now we will also give the label index using orient function. In this case the index of oreint will be assign to the columns and keys will assign to the rows

In [57]:
df_from_dict_label_index = pd.DataFrame.from_dict({'A': [1,2,3], 'B': [4,5,6],'C':[7,8,9]}, orient='index', columns=['col1', 'col2', 'col3' ])
df_from_dict_label_index

   col1  col2  col3
A     1     2     3
B     4     5     6
C     7     8     9

In [58]:
# Now we will try to change the names of keys and set them as row name
df_from_dict_label_index1 = pd.DataFrame.from_dict({'Row1': [1,2,3], 'Row2': [4,5,6],'Row3':[7,8,9]}, orient='index', columns=['col1', 'col2', 'col3' ]) 
df_from_dict_label_index1

      col1  col2  col3
Row1     1     2     3
Row2     4     5     6
Row3     7     8     9

In [ ]:
df_movies1 = pd.read_csv('Datasets/imdb_top_1000.csv ')
df_movies1.head()
# By default head will take only first 5

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [65]:
# Now we will apply filtering on this to get only specific columns
df_filtering = df_movies1['Released_Year']
df_filtering.head()

0    1994
1    1972
2    2008
3    1974
4    1957
Name: Released_Year, dtype: str

In [69]:
# Now we will apply facny indexing by getting multiple columns 
df_fancy_indexing = df_movies1[['Released_Year', 'Series_Title', 'IMDB_Rating']]
df_fancy_indexing.head()

  Released_Year              Series_Title  IMDB_Rating
0          1994  The Shawshank Redemption          9.3
1          1972             The Godfather          9.2
2          2008           The Dark Knight          9.0
3          1974    The Godfather: Part II          9.0
4          1957              12 Angry Men          9.0

In [ ]:
# Now we will apply loc and iloc for filtering data on rows and columns 
# loc will get lable index 
df_movies1.loc[0:5:,'Poster_Link':'Certificate']

,Poster_Link,Series_Title,Released_Year,Certificate
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,2003,U

In [73]:
# Now we will apply iloc that will get numeric index
df_movies1.iloc[0:3:,0:3]

,Poster_Link,Series_Title,Released_Year
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008

In [82]:
# Now we will apply boolean indexing with conditions 
# df_boolean_indexing['Recomended'] = df_movies1['Realized_Year'] > 2000
# df_boolean_indexing.head()

# df_movies['should_watch'] = df_movies['IMDB_Rating'] > 7
# df_movies.head()

df_movies1['Recomended'] = df_movies1['Certificate'] == 'A'
df_movies1.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Recomended
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",True
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",True
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444",False
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",True
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",False

axis = 0 : Means this will apply in row wise 
asix = 1 : Means this will apply in columns wise

In [ ]:
# Now we will apply drop method to remove columns 
# For when we will appl inplace true then the column will be removed
df_movies1.drop('Released_Year', axis = 1, inplace = True)
df_movies1.head()

,Poster_Link,Series_Title,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Recomended
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",True
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",True
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444",False
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",True
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",False

In [100]:
df_movies1.drop(0, axis=0, inplace=True)
df_movies1.head()

,Poster_Link,Series_Title,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Recomended
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",True
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",True
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",False
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905",False
6,https://m.media-amazon.com/images/M/MV5BNGNhMD...,Pulp Fiction,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",94.0,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1826188,"107,928,762",True

In [111]:
# Now we will apply drop using fancy indexing 
data = pd.read_csv("Datasets/imdb_top_1000.csv")
data.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [124]:
data.drop(data.columns[0:2], axis=1, inplace=True)
data.head()

,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
10,8.8,A meek Hobbit from the Shire and eight compani...,92.0,Peter Jackson,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,1661481,"315,544,750"
12,8.8,A bounty hunting scam joins two men in an unea...,90.0,Sergio Leone,Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo Giuffrè,688390,"6,100,000"
14,8.7,When a beautiful stranger leads computer hacke...,73.0,Lana Wachowski,Lilly Wachowski,Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss,1676426,"171,479,930"
15,8.7,The story of Henry Hill and his life in the mo...,90.0,Martin Scorsese,Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,1020727,"46,836,394"
16,8.7,After the Rebels are brutally overpowered by t...,82.0,Irvin Kershner,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,1159315,"290,475,067"

In [125]:
pratice = pd.read_csv('Datasets/imdb_top_1000.csv')
pratice.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"