In [34]:
import numpy as np
import pandas as pd

In [35]:
sales = pd.read_csv('Datasets/sales_data_sample.csv', sep=',', encoding='latin1')
sales.sort_index(inplace=True)
sales.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [36]:
sales_data = pd.read_csv('Datasets//sales_data.csv')
sales_data.sort_index(inplace=True)
sales_data.head()

        City Product     Category Salesperson  Quantity   Sales
0    Karachi  Laptop  Electronics         Ali         2  140000
1     Lahore  Mobile  Electronics        Sara         3   90000
2    Karachi  Mobile  Electronics       Ahmed         1   30000
3  Islamabad  Laptop  Electronics        Sara         1   70000
4     Lahore   Shirt     Clothing       Bilal         5    7500

In [37]:
gp  = sales_data.groupby('City')
gp

In [38]:
gp.groups

{'Islamabad': [3, 6, 9, 12, 15, 18], 'Karachi': [0, 2, 5, 8, 11, 14, 17], 'Lahore': [1, 4, 7, 10, 13, 16, 19]}

In [39]:
# Now we want to get only a specific group
gp.get_group('Lahore')

      City Product     Category Salesperson  Quantity   Sales
1   Lahore  Mobile  Electronics        Sara         3   90000
4   Lahore   Shirt     Clothing       Bilal         5    7500
7   Lahore  Laptop  Electronics       Bilal         1   70000
10  Lahore   Jeans     Clothing       Ahmed         2    6000
13  Lahore  Mobile  Electronics         Ali         2   60000
16  Lahore   Shirt     Clothing        Sara         3    4500
19  Lahore  Laptop  Electronics         Ali         2  140000

In [40]:
gp.get_group('Karachi')

       City Product     Category Salesperson  Quantity   Sales
0   Karachi  Laptop  Electronics         Ali         2  140000
2   Karachi  Mobile  Electronics       Ahmed         1   30000
5   Karachi   Shirt     Clothing         Ali         4    6000
8   Karachi   Jeans     Clothing        Sara         3    9000
11  Karachi  Laptop  Electronics       Bilal         1   70000
14  Karachi  Mobile  Electronics       Bilal         3   90000
17  Karachi   Jeans     Clothing       Ahmed         1    3000

In [41]:
gp.get_group('Islamabad')

         City Product     Category Salesperson  Quantity   Sales
3   Islamabad  Laptop  Electronics        Sara         1   70000
6   Islamabad  Mobile  Electronics       Ahmed         2   60000
9   Islamabad   Shirt     Clothing         Ali         6    9000
12  Islamabad   Jeans     Clothing        Sara         4   12000
15  Islamabad  Laptop  Electronics       Ahmed         2  140000
18  Islamabad  Mobile  Electronics       Bilal         1   30000

In [42]:
# This will only return total sales of all cities 
gp['Sales'].sum()

City
Islamabad    321000
Karachi      348000
Lahore       378000
Name: Sales, dtype: int64

In [43]:
# Now we will get only sales of one city like Islamabad
gp.get_group('Islamabad')['Sales'].sum()

np.int64(321000)

In [44]:
gp.get_group('Lahore')['Sales'].sum()

np.int64(378000)

In [45]:
gp.get_group('Karachi')['Category'].unique()

<StringArray>
['Electronics', 'Clothing']
Length: 2, dtype: str

In [46]:
# Now we will apply aggregated function on the groupby object
gp.get_group('Islamabad')['Sales'].agg([np.sum, np.mean, np.std])

sum     321000.000000
mean     53500.000000
std      44817.221392
Name: Sales, dtype: float64

In [47]:
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
pratice = pd.read_csv('Datasets/sales_data.csv')
pratice.sort_index(inplace=True)
pratice.head()

        City Product     Category Salesperson  Quantity   Sales
0    Karachi  Laptop  Electronics         Ali         2  140000
1     Lahore  Mobile  Electronics        Sara         3   90000
2    Karachi  Mobile  Electronics       Ahmed         1   30000
3  Islamabad  Laptop  Electronics        Sara         1   70000
4     Lahore   Shirt     Clothing       Bilal         5    7500

In [49]:
# Sales of each City
pratice.groupby('City', as_index=True)['Sales'].sum()

City
Islamabad    321000
Karachi      348000
Lahore       378000
Name: Sales, dtype: int64

In [50]:
# Average quantity of each product
pratice.groupby('Product')['Quantity'].mean()

Product
Jeans     2.5
Laptop    1.5
Mobile    2.0
Shirt     4.5
Name: Quantity, dtype: float64

In [51]:
pratice.groupby('Category').count()

pratice.groupby('Category').size()

Category
Clothing        8
Electronics    12
dtype: int64

In [52]:
pratice.groupby('Salesperson')['Sales'].sum().sort_values(ascending=False)

Salesperson
Ali      355000
Bilal    267500
Ahmed    239000
Sara     185500
Name: Sales, dtype: int64

In [53]:
pratice.groupby(['City', 'Product'])['Sales'].sum()

City       Product
Islamabad  Jeans       12000
           Laptop     210000
           Mobile      90000
           Shirt        9000
Karachi    Jeans       12000
           Laptop     210000
           Mobile     120000
           Shirt        6000
Lahore     Jeans        6000
           Laptop     210000
           Mobile     150000
           Shirt       12000
Name: Sales, dtype: int64

In [54]:
pratice.groupby('Salesperson')['Sales'].agg(['max', 'min'])

                max   min
Salesperson
Ahmed        140000  3000
Ali          140000  6000
Bilal         90000  7500
Sara          90000  4500

In [55]:
pratice2 = pd.read_csv("Datasets/sales_data.csv")
pratice2.sort_index(inplace=True)
pratice2.head()

        City Product     Category Salesperson  Quantity   Sales
0    Karachi  Laptop  Electronics         Ali         2  140000
1     Lahore  Mobile  Electronics        Sara         3   90000
2    Karachi  Mobile  Electronics       Ahmed         1   30000
3  Islamabad  Laptop  Electronics        Sara         1   70000
4     Lahore   Shirt     Clothing       Bilal         5    7500

In [56]:
k = pratice2.groupby('City')
k

In [57]:
karachi_data = k.get_group('Karachi')['Sales'].mean()
karachi_data

np.float64(49714.28571428572)

In [58]:
k2 = pratice2.groupby(['Category','Quantity','Sales'])
k2

In [59]:
sale = pd.read_csv("Datasets/sales_data.csv")
sale.sort_index(inplace=True)   
sale.head()

        City Product     Category Salesperson  Quantity   Sales
0    Karachi  Laptop  Electronics         Ali         2  140000
1     Lahore  Mobile  Electronics        Sara         3   90000
2    Karachi  Mobile  Electronics       Ahmed         1   30000
3  Islamabad  Laptop  Electronics        Sara         1   70000
4     Lahore   Shirt     Clothing       Bilal         5    7500

In [61]:
date = pd.read_csv("Datasets/sales_wide.csv")
date.sort_index(inplace=True)   
date.head()

     Name        Date  Math  Science  English
0     Ali  2024-01-05    85       90       88
1    Sara  2024-01-05    78       82       91
2   Bilal  2024-01-06    92       75       80
3  Ayesha  2024-01-06    88       95       90
4     Ali  2024-02-05    89       91       85

In [62]:
date['Date'].dtype

In [63]:
date['Date'] = pd.to_datetime(date['Date'])
date['Date']

0   2024-01-05
1   2024-01-05
2   2024-01-06
3   2024-01-06
4   2024-02-05
5   2024-02-05
Name: Date, dtype: datetime64[us]

In [64]:
date['Month'] = date['Date'].dt.month
date['Month']

0    1
1    1
2    1
3    1
4    2
5    2
Name: Month, dtype: int32