In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Long DataFormat and Wide DataFormat

In [7]:
wide_data = pd.DataFrame({'Std_ID': [1, 2, 3, 4, 5],'Marks': [10, 20, 30, 40, 50],
'Fee': [1000, 2000, 3000, 4000, 5000], 'Subject': ['Math', 'Physics', 'Chemistry', 'Biology', 'English'],
'Age': [15, 16, 17, 18, 19]})

wide_data

   Std_ID  Marks   Fee    Subject  Age
0       1     10  1000       Math   15
1       2     20  2000    Physics   16
2       3     30  3000  Chemistry   17
3       4     40  4000    Biology   18
4       5     50  5000    English   19

In [14]:
# Now we will convert the wide data into long data using melt()
long_data = wide_data.melt(id_vars=['Std_ID', 'Subject'], var_name='Variable', value_name='Value')
long_data

    Std_ID    Subject Variable  Value
0        1       Math    Marks     10
1        2    Physics    Marks     20
2        3  Chemistry    Marks     30
3        4    Biology    Marks     40
4        5    English    Marks     50
5        1       Math      Fee   1000
6        2    Physics      Fee   2000
7        3  Chemistry      Fee   3000
8        4    Biology      Fee   4000
9        5    English      Fee   5000
10       1       Math      Age     15
11       2    Physics      Age     16
12       3  Chemistry      Age     17
13       4    Biology      Age     18
14       5    English      Age     19

In [19]:
# Now we will convert the long data into wide data using pivot()
long_data.pivot(index=['Std_ID', 'Subject'], columns='Variable', values='Value').reset_index()

Variable  Std_ID    Subject  Age   Fee  Marks
0              1       Math   15  1000     10
1              2    Physics   16  2000     20
2              3  Chemistry   17  3000     30
3              4    Biology   18  4000     40
4              5    English   19  5000     50

# Merge Funtion

In [20]:
data1 = pd.DataFrame({'Std_ID': [1, 2, 3, 4, 5],'Marks': [10, 20, 30, 40, 50],
'Fee': [1000, 2000, 3000, 4000, 5000], 'Subject': ['Math', 'Physics', 'Chemistry', 'Biology', 'English'],
'Age': [15, 16, 17, 18, 19]})
data1

   Std_ID  Marks   Fee    Subject  Age
0       1     10  1000       Math   15
1       2     20  2000    Physics   16
2       3     30  3000  Chemistry   17
3       4     40  4000    Biology   18
4       5     50  5000    English   19

In [24]:
data2 = pd.DataFrame({'Std_ID': [1, 2, 3, 4, 5],'Marks': [10, 20, 30, 40, 50],
'Charges': [1000, 2000, 3000, 4000, 5000], 'Course': ['Math', 'Physics', 'Chemistry', 'Biology', 'English'],
'Old': [15, 16, 17, 18, 19]})
data2

   Std_ID  Marks  Charges     Course  Old
0       1     10     1000       Math   15
1       2     20     2000    Physics   16
2       3     30     3000  Chemistry   17
3       4     40     4000    Biology   18
4       5     50     5000    English   19

In [26]:
data3 = pd.concat([data1, data2], axis=0, ignore_index=True)
data3

   Std_ID  Marks     Fee    Subject   Age  Charges     Course   Old
0       1     10  1000.0       Math  15.0      NaN        NaN   NaN
1       2     20  2000.0    Physics  16.0      NaN        NaN   NaN
2       3     30  3000.0  Chemistry  17.0      NaN        NaN   NaN
3       4     40  4000.0    Biology  18.0      NaN        NaN   NaN
4       5     50  5000.0    English  19.0      NaN        NaN   NaN
5       1     10     NaN        NaN   NaN   1000.0       Math  15.0
6       2     20     NaN        NaN   NaN   2000.0    Physics  16.0
7       3     30     NaN        NaN   NaN   3000.0  Chemistry  17.0
8       4     40     NaN        NaN   NaN   4000.0    Biology  18.0
9       5     50     NaN        NaN   NaN   5000.0    English  19.0

In [32]:
# Now will apply the merge() method to combine data1 and data2 based on the common column 'Std_ID'
merged_data = pd.merge(data1, data2, on='Std_ID', how='right')
merged_data

   Std_ID  Marks_x   Fee    Subject  Age  Marks_y  Charges     Course  Old
0       1       10  1000       Math   15       10     1000       Math   15
1       2       20  2000    Physics   16       20     2000    Physics   16
2       3       30  3000  Chemistry   17       30     3000  Chemistry   17
3       4       40  4000    Biology   18       40     4000    Biology   18
4       5       50  5000    English   19       50     5000    English   19