In [50]:
import numpy as np
import pandas as pd

In [51]:
df_sales = pd.read_csv('Datasets/sales_data_sample.csv', sep=',', encoding='latin1')
df_sales.sort_index()
df_sales.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [52]:
df_sales.set_index(['PRICEEACH','SALES'], inplace=True)
df_sales.head()

,,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
PRICEEACH,SALES,,,,,,,,,,,,,,,,,,,,,
95.70,2871.00,10107,30,2,2/24/2003 0:00,Shipped,1,2,2003,Motorcycles,95,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
81.35,2765.90,10121,34,5,5/7/2003 0:00,Shipped,2,5,2003,Motorcycles,95,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
94.74,3884.34,10134,41,2,7/1/2003 0:00,Shipped,3,7,2003,Motorcycles,95,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
83.26,3746.70,10145,45,6,8/25/2003 0:00,Shipped,3,8,2003,Motorcycles,95,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
100.00,5205.27,10159,49,14,10/10/2003 0:00,Shipped,4,10,2003,Motorcycles,95,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [53]:
df_sales.index

MultiIndex([( 95.7,  2871.0),
            (81.35,  2765.9),
            (94.74, 3884.34),
            (83.26,  3746.7),
            (100.0, 5205.27),
            (96.66, 3479.76),
            (86.13, 2497.77),
            (100.0, 5512.32),
            (98.57, 2168.54),
            (100.0, 4708.44),
            ...
            (60.06, 1921.92),
            (59.51, 2082.85),
            (55.69,  2227.6),
            (86.74, 3209.38),
            (97.16, 4080.72),
            (100.0,  2244.4),
            (100.0, 3978.51),
            (100.0, 5417.57),
            (62.24, 2116.16),
            (65.52, 3079.44)],
           names=['PRICEEACH', 'SALES'], length=2823)

In [54]:
df_sales.index.levels

FrozenList([[26.88, 27.22, 28.29, 28.88, 29.21, 29.54, 29.7, 29.87, 30.06, 30.2, 30.59, 30.96, 31.12, 31.2, 31.47, 31.53, 31.82, 31.86, 32.1, 32.47, 32.59, 32.88, 32.99, 33.19, 33.23, 33.24, 34.19, 34.36, 34.47, 34.88, 34.91, 35.18, 35.29, 35.35, 35.4, 35.49, 35.51, 35.71, 35.8, 35.87, 36.07, 36.11, 36.21, 36.29, 36.42, 36.61, 36.63, 36.66, 36.74, 36.84, 36.93, 37.0, 37.13, 37.17, 37.18, 37.34, 37.48, 37.5, 37.63, 37.84, 37.97, 38.08, 38.17, 38.19, 38.22, 38.4, 38.5, 38.52, 38.89, 38.9, 38.98, 39.42, 39.43, 39.6, 39.65, 39.8, 39.83, 40.15, 40.21, 40.22, 40.23, 40.25, 40.31, 40.4, 40.62, 40.66, 41.02, 41.03, 41.22, 41.54, 41.71, 41.72, 41.85, 41.91, 42.24, 42.26, 42.43, 42.64, 42.67, 42.76, ...], [482.13, 541.14, 553.95, 577.6, 640.05, 651.8, 652.35, 683.8, 694.6, 703.6, 710.2, 717.4, 721.44, 728.4, 733.11, 759.46, 777.0, 785.64, 813.2, 820.4, 828.36, 834.67, 845.25, 846.51, 856.52, 859.14, 865.49, 875.91, 881.4, 891.03, 891.2, 902.66, 905.28, 913.92, 917.7, 925.3, 930.9, 935.18, 948.99, 965.04, 971.98, 972.4, 974.1, 974.82, 977.43, 977.67, 981.2, 988.47, 990.78, 995.5, 1007.14, 1012.4, 1013.48, 1013.76, 1030.44, 1033.41, 1035.58, 1045.98, 1056.4, 1057.29, 1057.56, 1063.65, 1066.75, 1082.1, 1085.04, 1086.6, 1089.36, 1092.2, 1093.99, 1103.76, 1104.6, 1105.25, 1106.93, 1108.38, 1109.8, 1112.94, 1113.6, 1119.93, 1122.4, 1129.04, 1134.0, 1135.31, 1138.94, 1140.48, 1142.41, 1146.5, 1151.44, 1152.06, 1152.58, 1161.12, 1163.05, 1164.4, 1167.25, 1172.34, 1172.6, 1173.15, 1175.16, 1185.3, 1189.44, 1189.98, ...]])

In [55]:
df_sales.index.get_level_values(0)

Index([ 95.7, 81.35, 94.74, 83.26, 100.0, 96.66, 86.13, 100.0, 98.57, 100.0,
       ...
       60.06, 59.51, 55.69, 86.74, 97.16, 100.0, 100.0, 100.0, 62.24, 65.52],
      dtype='float64', name='PRICEEACH', length=2823)

In [56]:
df_sales.index.get_level_values(1)

Index([ 2871.0,  2765.9, 3884.34,  3746.7, 5205.27, 3479.76, 2497.77, 5512.32,
       2168.54, 4708.44,
       ...
       1921.92, 2082.85,  2227.6, 3209.38, 4080.72,  2244.4, 3978.51, 5417.57,
       2116.16, 3079.44],
      dtype='float64', name='SALES', length=2823)

In [57]:
df_sales.index.get_level_values('PRICEEACH')

Index([ 95.7, 81.35, 94.74, 83.26, 100.0, 96.66, 86.13, 100.0, 98.57, 100.0,
       ...
       60.06, 59.51, 55.69, 86.74, 97.16, 100.0, 100.0, 100.0, 62.24, 65.52],
      dtype='float64', name='PRICEEACH', length=2823)

In [58]:
df_sales.index.get_level_values('SALES')

Index([ 2871.0,  2765.9, 3884.34,  3746.7, 5205.27, 3479.76, 2497.77, 5512.32,
       2168.54, 4708.44,
       ...
       1921.92, 2082.85,  2227.6, 3209.38, 4080.72,  2244.4, 3978.51, 5417.57,
       2116.16, 3079.44],
      dtype='float64', name='SALES', length=2823)

In [59]:
multi_index = pd.read_csv('Datasets/sales_data_sample.csv', sep=',', encoding='latin1')
multi_index.sort_index(inplace=True)
multi_index.head()

multi_index.set_index(['PRICEEACH','SALES'], inplace=True)
multi_index.head()

,,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
PRICEEACH,SALES,,,,,,,,,,,,,,,,,,,,,
95.70,2871.00,10107,30,2,2/24/2003 0:00,Shipped,1,2,2003,Motorcycles,95,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
81.35,2765.90,10121,34,5,5/7/2003 0:00,Shipped,2,5,2003,Motorcycles,95,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
94.74,3884.34,10134,41,2,7/1/2003 0:00,Shipped,3,7,2003,Motorcycles,95,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
83.26,3746.70,10145,45,6,8/25/2003 0:00,Shipped,3,8,2003,Motorcycles,95,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
100.00,5205.27,10159,49,14,10/10/2003 0:00,Shipped,4,10,2003,Motorcycles,95,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [60]:
idx1 = pd.IndexSlice
multi_index.loc[idx1[95.70,:],:]

,,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
PRICEEACH,SALES,,,,,,,,,,,,,,,,,,,,,
95.7,2871.0,10107,30,2,2/24/2003 0:00,Shipped,1,2,2003,Motorcycles,95,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small

In [61]:
sort = multi_index.sort_index()
sort.loc[idx1[80:100, :], :]

                    ORDERNUMBER  QUANTITYORDERED  ORDERLINENUMBER  \
PRICEEACH SALES
80.00     3440.00         10327               43                2
80.10     3204.00         10267               40                5
80.34     2169.18         10159               27               11
          2972.58         10224               37                4
80.41     2171.07         10310               27               13
...                         ...              ...              ...
100.00    11886.60        10403               66                9
          11887.80        10412               60                9
          12001.00        10424               50                6
          12536.50        10322               50                6
          14082.80        10407               76                2

                          ORDERDATE      STATUS  QTR_ID  MONTH_ID  YEAR_ID  \
PRICEEACH SALES
80.00     3440.00   11/10/2004 0:00    Resolved       4        11     2004
80.10     3204.00     7/7/2004 0:00     Shipped       3         7     2004
80.34     2169.18   10/10/2003 0:00     Shipped       4        10     2003
          2972.58    2/21/2004 0:00     Shipped       1         2     2004
80.41     2171.07   10/16/2004 0:00     Shipped       4        10     2004
...                             ...         ...     ...       ...      ...
100.00    11886.60    4/8/2005 0:00     Shipped       2         4     2005
          11887.80    5/3/2005 0:00     Shipped       2         5     2005
          12001.00   5/31/2005 0:00  In Process       2         5     2005
          12536.50   11/4/2004 0:00     Shipped       4        11     2004
          14082.80   4/22/2005 0:00     On Hold       2         4     2005

                     PRODUCTLINE  MSRP  ...                  ADDRESSLINE1  \
PRICEEACH SALES                         ...
80.00     3440.00          Ships   100  ...                  Vinb'ltet 34
80.10     3204.00   Classic Cars    73  ...             4092 Furth Circle
80.34     2169.18    Motorcycles    69  ...               7734 Strong St.
          2972.58    Motorcycles    69  ...       184, chausse de Tournai
80.41     2171.07   Classic Cars    80  ...            Mehrheimerstr. 369
...                          ...   ...  ...                           ...
100.00    11886.60   Motorcycles   193  ...  Berkeley Gardens 12  Brewery
          11887.80  Classic Cars   169  ...            C/ Moralzarzal, 86
          12001.00  Classic Cars   214  ...            C/ Moralzarzal, 86
          12536.50  Vintage Cars   127  ...      2304 Long Airport Avenue
          14082.80  Vintage Cars   170  ...                3086 Ingle Ln.

                   ADDRESSLINE2           CITY STATE POSTALCODE  COUNTRY  \
PRICEEACH SALES
80.00     3440.00           NaN      Kobenhavn   NaN       1734  Denmark
80.10     3204.00     Suite 400            NYC    NY      10022      USA
80.34     2169.18           NaN  San Francisco    CA        NaN      USA
          2972.58           NaN          Lille   NaN      59000   France
80.41     2171.07           NaN           Koln   NaN      50739  Germany
...                         ...            ...   ...        ...      ...
100.00    11886.60          NaN      Liverpool   NaN    WX1 6LT       UK
          11887.80          NaN         Madrid   NaN      28034    Spain
          12001.00          NaN         Madrid   NaN      28034    Spain
          12536.50          NaN         Nashua    NH      62005      USA
          14082.80          NaN       San Jose    CA      94217      USA

                   TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
PRICEEACH SALES
80.00     3440.00       EMEA        Petersen            Jytte   Medium
80.10     3204.00        NaN           Young             Jeff   Medium
80.34     2169.18        NaN           Brown            Julie    Small
          2972.58       EMEA           Rance          Martine    Small
80.41     2171.07       EMEA       Pfalzheim        Henriette    Small
...                      ...             ...              ...      ...
100.00    11886.60      EMEA           Devon        Elizabeth    Large
          11887.80      EMEA          Freyre            Diego    Large
          12001.00      EMEA          Freyre            Diego    Large
          12536.50       NaN           Young          Valarie    Large
          14082.80       NaN           Frick              Sue    Large

[1821 rows x 23 columns]

In [62]:
sort2 = multi_index.sort_index()
sort2.loc[idx1[80:100, 2000:3000],'ORDERNUMBER':'ORDERLINENUMBER']
sort2.head()

,,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
PRICEEACH,SALES,,,,,,,,,,,,,,,,,,,,,
26.88,1209.60,10420,45,1,5/29/2005 0:00,In Process,2,5,2005,Vintage Cars,33,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small
27.22,1007.14,10162,37,5,10/18/2003 0:00,Shipped,4,10,2003,Vintage Cars,33,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Small
28.29,905.28,10195,32,7,11/25/2003 0:00,Shipped,4,11,2003,Classic Cars,35,...,3758 North Pendale Street,NaN,White Plains,NY,24067,USA,NaN,Frick,Steve,Small
28.88,577.60,10280,20,12,8/17/2004 0:00,Shipped,3,8,2004,Vintage Cars,33,...,Via Monte Bianco 34,NaN,Torino,NaN,10100,Italy,EMEA,Accorti,Paolo,Small
29.21,759.46,10193,26,10,11/21/2003 0:00,Shipped,4,11,2003,Vintage Cars,33,...,7 Allen Street,NaN,Glen Waverly,Victoria,3150,Australia,APAC,Connery,Sean,Small

In [63]:
df_multi_index = pd.read_csv("Datasets/sales_data_sample.csv", sep=",", encoding="latin1")
df_multi_index.sort_index(inplace=True)
df_multi_index.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [64]:
df_multi_index.set_index(['ORDERNUMBER','QUANTITYORDERED','PRICEEACH'], inplace=True)
df_multi_index.head()

,,,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,PRODUCTCODE,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
ORDERNUMBER,QUANTITYORDERED,PRICEEACH,,,,,,,,,,,,,,,,,,,,,
10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,Motorcycles,95,S10_1678,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,Motorcycles,95,S10_1678,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,Motorcycles,95,S10_1678,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,Motorcycles,95,S10_1678,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,Motorcycles,95,S10_1678,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [67]:
slice_idx = pd.IndexSlice
df_multi_index.sort_index(inplace=True)
df_multi_index.loc[slice_idx[::,::,80.00:90.00,:],:]
df_multi_index.head()

                                       ORDERLINENUMBER    SALES  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51                    4  1903.22
            30              100.00                   3  5151.00
            49              34.47                    1  1689.03
            50              67.80                    2  3390.00
10101       25              100.00                   4  3782.00

                                           ORDERDATE   STATUS  QTR_ID  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51      1/6/2003 0:00  Shipped       1
            30              100.00     1/6/2003 0:00  Shipped       1
            49              34.47      1/6/2003 0:00  Shipped       1
            50              67.80      1/6/2003 0:00  Shipped       1
10101       25              100.00     1/9/2003 0:00  Shipped       1

                                       MONTH_ID  YEAR_ID   PRODUCTLINE  MSRP  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51             1     2003  Vintage Cars    92
            30              100.00            1     2003  Vintage Cars   170
            49              34.47             1     2003  Vintage Cars    41
            50              67.80             1     2003  Vintage Cars    60
10101       25              100.00            1     2003  Vintage Cars   127

                                      PRODUCTCODE  ...  \
ORDERNUMBER QUANTITYORDERED PRICEEACH              ...
10100       22              86.51        S18_4409  ...
            30              100.00       S18_1749  ...
            49              34.47        S24_3969  ...
            50              67.80        S18_2248  ...
10101       25              100.00       S18_2325  ...

                                                   ADDRESSLINE1 ADDRESSLINE2  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51      2304 Long Airport Avenue          NaN
            30              100.00     2304 Long Airport Avenue          NaN
            49              34.47      2304 Long Airport Avenue          NaN
            50              67.80      2304 Long Airport Avenue          NaN
10101       25              100.00                Lyonerstr. 34          NaN

                                            CITY STATE POSTALCODE  COUNTRY  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51         Nashua    NH      62005      USA
            30              100.00        Nashua    NH      62005      USA
            49              34.47         Nashua    NH      62005      USA
            50              67.80         Nashua    NH      62005      USA
10101       25              100.00     Frankfurt   NaN      60528  Germany

                                      TERRITORY CONTACTLASTNAME  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51           NaN           Young
            30              100.00          NaN           Young
            49              34.47           NaN           Young
            50              67.80           NaN           Young
10101       25              100.00         EMEA          Keitel

                                      CONTACTFIRSTNAME DEALSIZE
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51              Valarie    Small
            30              100.00             Valarie   Medium
            49              34.47              Valarie    Small
            50              67.80              Valarie   Medium
10101       25              100.00              Roland   Medium

[5 rows x 22 columns]

In [70]:
slice_idx2 = pd.IndexSlice
df_multi_index.sort_index(inplace=True)
df_multi_index.loc[slice_idx2[::,::,80.00:90.00],'SALES':'YEAR_ID']
df_multi_index.head()

                                       ORDERLINENUMBER    SALES  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51                    4  1903.22
            30              100.00                   3  5151.00
            49              34.47                    1  1689.03
            50              67.80                    2  3390.00
10101       25              100.00                   4  3782.00

                                           ORDERDATE   STATUS  QTR_ID  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51      1/6/2003 0:00  Shipped       1
            30              100.00     1/6/2003 0:00  Shipped       1
            49              34.47      1/6/2003 0:00  Shipped       1
            50              67.80      1/6/2003 0:00  Shipped       1
10101       25              100.00     1/9/2003 0:00  Shipped       1

                                       MONTH_ID  YEAR_ID   PRODUCTLINE  MSRP  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51             1     2003  Vintage Cars    92
            30              100.00            1     2003  Vintage Cars   170
            49              34.47             1     2003  Vintage Cars    41
            50              67.80             1     2003  Vintage Cars    60
10101       25              100.00            1     2003  Vintage Cars   127

                                      PRODUCTCODE  ...  \
ORDERNUMBER QUANTITYORDERED PRICEEACH              ...
10100       22              86.51        S18_4409  ...
            30              100.00       S18_1749  ...
            49              34.47        S24_3969  ...
            50              67.80        S18_2248  ...
10101       25              100.00       S18_2325  ...

                                                   ADDRESSLINE1 ADDRESSLINE2  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51      2304 Long Airport Avenue          NaN
            30              100.00     2304 Long Airport Avenue          NaN
            49              34.47      2304 Long Airport Avenue          NaN
            50              67.80      2304 Long Airport Avenue          NaN
10101       25              100.00                Lyonerstr. 34          NaN

                                            CITY STATE POSTALCODE  COUNTRY  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51         Nashua    NH      62005      USA
            30              100.00        Nashua    NH      62005      USA
            49              34.47         Nashua    NH      62005      USA
            50              67.80         Nashua    NH      62005      USA
10101       25              100.00     Frankfurt   NaN      60528  Germany

                                      TERRITORY CONTACTLASTNAME  \
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51           NaN           Young
            30              100.00          NaN           Young
            49              34.47           NaN           Young
            50              67.80           NaN           Young
10101       25              100.00         EMEA          Keitel

                                      CONTACTFIRSTNAME DEALSIZE
ORDERNUMBER QUANTITYORDERED PRICEEACH
10100       22              86.51              Valarie    Small
            30              100.00             Valarie   Medium
            49              34.47              Valarie    Small
            50              67.80              Valarie   Medium
10101       25              100.00              Roland   Medium

[5 rows x 22 columns]

In [71]:
tuple_slicing = pd.read_csv("Datasets/sales_data_sample.csv", sep=",", encoding="latin1")
tuple_slicing.sort_index(inplace=True)
tuple_slicing.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [72]:
tuple_slicing.set_index(['ORDERNUMBER','QUANTITYORDERED','ORDERLINENUMBER'], inplace=True)
tuple_slicing.head()

,,,PRICEEACH,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,PRODUCTCODE,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,,,,,,,,,,,,,,,,,,,,,
10107,30,2,95.70,2871.00,2/24/2003 0:00,Shipped,1,2,2003,Motorcycles,95,S10_1678,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
10121,34,5,81.35,2765.90,5/7/2003 0:00,Shipped,2,5,2003,Motorcycles,95,S10_1678,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
10134,41,2,94.74,3884.34,7/1/2003 0:00,Shipped,3,7,2003,Motorcycles,95,S10_1678,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
10145,45,6,83.26,3746.70,8/25/2003 0:00,Shipped,3,8,2003,Motorcycles,95,S10_1678,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
10159,49,14,100.00,5205.27,10/10/2003 0:00,Shipped,4,10,2003,Motorcycles,95,S10_1678,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
t = pd.IndexSlice
tuple_slicing.sort_index(inplace=True)
tuple_slicing.loc[t[10107:10159:,20:40:,::],:]
tuple_slicing.head()

                                             PRICEEACH    SALES  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10100       22              4                    86.51  1903.22
            30              3                   100.00  5151.00
            49              1                    34.47  1689.03
            50              2                    67.80  3390.00
10101       25              4                   100.00  3782.00

                                                 ORDERDATE   STATUS  QTR_ID  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10100       22              4                1/6/2003 0:00  Shipped       1
            30              3                1/6/2003 0:00  Shipped       1
            49              1                1/6/2003 0:00  Shipped       1
            50              2                1/6/2003 0:00  Shipped       1
10101       25              4                1/9/2003 0:00  Shipped       1

                                             MONTH_ID  YEAR_ID   PRODUCTLINE  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10100       22              4                       1     2003  Vintage Cars
            30              3                       1     2003  Vintage Cars
            49              1                       1     2003  Vintage Cars
            50              2                       1     2003  Vintage Cars
10101       25              4                       1     2003  Vintage Cars

                                             MSRP PRODUCTCODE  ...  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER                    ...
10100       22              4                  92    S18_4409  ...
            30              3                 170    S18_1749  ...
            49              1                  41    S24_3969  ...
            50              2                  60    S18_2248  ...
10101       25              4                 127    S18_2325  ...

                                                         ADDRESSLINE1  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10100       22              4                2304 Long Airport Avenue
            30              3                2304 Long Airport Avenue
            49              1                2304 Long Airport Avenue
            50              2                2304 Long Airport Avenue
10101       25              4                           Lyonerstr. 34

                                            ADDRESSLINE2       CITY STATE  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10100       22              4                        NaN     Nashua    NH
            30              3                        NaN     Nashua    NH
            49              1                        NaN     Nashua    NH
            50              2                        NaN     Nashua    NH
10101       25              4                        NaN  Frankfurt   NaN

                                            POSTALCODE  COUNTRY TERRITORY  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10100       22              4                    62005      USA       NaN
            30              3                    62005      USA       NaN
            49              1                    62005      USA       NaN
            50              2                    62005      USA       NaN
10101       25              4                    60528  Germany      EMEA

                                            CONTACTLASTNAME CONTACTFIRSTNAME  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10100       22              4                         Young          Valarie
            30              3                         Young          Valarie
            49              1                         Young          Valarie
            50              2                         Young          Valarie
10101       25              4                        Keitel           Roland

                                            DEALSIZE
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10100       22              4                  Small
            30              3                 Medium
            49              1                  Small
            50              2                 Medium
10101       25              4                 Medium

[5 rows x 22 columns]

In [87]:
print(tuple_slicing.loc[[10107]].head())

                                             PRICEEACH    SALES  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10107       20              8                    92.90  1858.00
            21              1                   100.00  3036.60
            25              3                   100.00  2845.75
            27              4                   100.00  6065.55
            29              6                    70.87  2055.23

                                                  ORDERDATE   STATUS  QTR_ID  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10107       20              8                2/24/2003 0:00  Shipped       1
            21              1                2/24/2003 0:00  Shipped       1
            25              3                2/24/2003 0:00  Shipped       1
            27              4                2/24/2003 0:00  Shipped       1
            29              6                2/24/2003 0:00  Shipped       1

                                             MONTH_ID  YEAR_ID  PRODUCTLINE  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10107       20              8                       2     2003  Motorcycles
            21              1                       2     2003  Motorcycles
            25              3                       2     2003  Motorcycles
            27              4                       2     2003  Motorcycles
            29              6                       2     2003  Motorcycles

                                             MSRP PRODUCTCODE  ...  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER                    ...
10107       20              8                  99    S32_1374  ...
            21              1                 150    S12_2823  ...
            25              3                 112    S24_1578  ...
            27              4                 193    S10_4698  ...
            29              6                  60    S18_2625  ...

                                                        ADDRESSLINE1  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10107       20              8                897 Long Airport Avenue
            21              1                897 Long Airport Avenue
            25              3                897 Long Airport Avenue
            27              4                897 Long Airport Avenue
            29              6                897 Long Airport Avenue

                                            ADDRESSLINE2 CITY STATE  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10107       20              8                        NaN  NYC    NY
            21              1                        NaN  NYC    NY
            25              3                        NaN  NYC    NY
            27              4                        NaN  NYC    NY
            29              6                        NaN  NYC    NY

                                            POSTALCODE COUNTRY TERRITORY  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10107       20              8                    10022     USA       NaN
            21              1                    10022     USA       NaN
            25              3                    10022     USA       NaN
            27              4                    10022     USA       NaN
            29              6                    10022     USA       NaN

                                            CONTACTLASTNAME CONTACTFIRSTNAME  \
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10107       20              8                            Yu             Kwai
            21              1                            Yu             Kwai
            25              3                            Yu             Kwai
            27              4                            Yu             Kwai
            29              6                            Yu             Kwai

                                            DEALSIZE
ORDERNUMBER QUANTITYORDERED ORDERLINENUMBER
10107       20              8                  Small
            21              1                 Medium
            25              3                  Small
            27              4                 Medium
            29              6                  Small

[5 rows x 22 columns]