In [137]:
import numpy as np
import pandas as pd

In [138]:
# House prices ka array banayein aur stats nikalein
prices = np.array([100,120,110,130,5000])

print("Mean of House Prices is:", prices.mean())
print("Median of House Prices is:", np.median(prices))
print("Std of House Prices is:", prices.std())

Mean of House Prices is: 1092.0
Median of House Prices is: 120.0
Std of House Prices is: 1954.025588368791

In [139]:
data = np.array([10, 20, 30, 40, 5000, 60, 70])

mask = data > 1000
mask

array([False, False, False, False,  True, False, False])

In [140]:
array = pd.Series([10,20,30,40], index=['a','b','c','d'])
array

a    10
b    20
c    30
d    40
dtype: int64

In [141]:
array.reset_index()

  index   0
0     a  10
1     b  20
2     c  30
3     d  40

In [142]:
a = pd.Series(np.arange(1,5), index=['a','b','c','d'])
a

a    1
b    2
c    3
d    4
dtype: int64

In [143]:
filtering = a.where(a>2)
filtering

a    NaN
b    NaN
c    3.0
d    4.0
dtype: float64

Filtering Data

In [144]:
fil = np.array([10,20,30,40,50])
fil

fil2 = np.where(fil>20, "Good",np.where(fil<30, "Normal", "Bad"))
fil2

array(['Normal', 'Normal', 'Good', 'Good', 'Good'], dtype='<U6')

In [145]:
number = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8], "C":[9,10,11,12]})
number

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [146]:
import pandas as pd

# Let's create a mock dataset of Smartphone Reviews
data = {
    'Brand': ['Apple', 'Samsung', 'Google', 'OnePlus', 'Xiaomi', 'Sony'],
    'Model': ['iPhone 15', 'Galaxy S24', 'Pixel 8', 'OnePlus 12', 'Redmi Note 13', 'Xperia 1 V'],
    'Release_Year': [2023, 2024, 2023, 2023, 2023, 2023],
    'Price': [799, 899, 699, 799, 299, 1399],
    'Battery_Life': [20, 24, 22, 28, 30, 18],
    'Camera_Rating': [9.5, 9.2, 9.4, 8.8, 8.0, 8.5],
    'OS': ['iOS', 'Android', 'Android', 'Android', 'Android', 'Android']
}

df_phones = pd.DataFrame(data)
df_phones.head()

,Brand,Model,Release_Year,Price,Battery_Life,Camera_Rating,OS
0,Apple,iPhone 15,2023,799,20,9.5,iOS
1,Samsung,Galaxy S24,2024,899,24,9.2,Android
2,Google,Pixel 8,2023,699,22,9.4,Android
3,OnePlus,OnePlus 12,2023,799,28,8.8,Android
4,Xiaomi,Redmi Note 13,2023,299,30,8.0,Android

In [147]:
three_rows = df_phones.head(3)
three_rows

,Brand,Model,Release_Year,Price,Battery_Life,Camera_Rating,OS
0,Apple,iPhone 15,2023,799,20,9.5,iOS
1,Samsung,Galaxy S24,2024,899,24,9.2,Android
2,Google,Pixel 8,2023,699,22,9.4,Android

In [148]:
df_specs = df_phones[['Model', 'Price']]
print(df_specs)

           Model  Price
0      iPhone 15    799
1     Galaxy S24    899
2        Pixel 8    699
3     OnePlus 12    799
4  Redmi Note 13    299
5     Xperia 1 V   1399

In [149]:
data = pd.read_csv("Datasets/people-100.csv")
data.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [150]:
# Apply indexing 
column_indexing = data.loc[::,'First Name':'Sex']
column_indexing.head()

  First Name Last Name     Sex
0     Shelby   Terrell    Male
1    Phillip   Summers  Female
2   Kristine    Travis    Male
3    Yesenia  Martinez    Male
4       Lori      Todd    Male

In [151]:
# Row and column indexing 
row_col_indexing = data.iloc[0:4,0:3]
row_col_indexing.head()

   Index          User Id First Name
0      1  88F7B33d2bcf9f5     Shelby
1      2  f90cD3E76f1A9b9    Phillip
2      3  DbeAb8CcdfeFC2c   Kristine
3      4  A31Bee3c201ef58    Yesenia

In [152]:
# Create a new column 
data['Salary'] = 0
data.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Salary
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer,0
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist,0
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath,0
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher,0
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon,0

In [153]:
pd.read_csv('Datasets/people-100.csv')

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [154]:
data['Salary'] = 0
print(data.head())

   Index          User Id First Name Last Name     Sex  \
0      1  88F7B33d2bcf9f5     Shelby   Terrell    Male
1      2  f90cD3E76f1A9b9    Phillip   Summers  Female
2      3  DbeAb8CcdfeFC2c   Kristine    Travis    Male
3      4  A31Bee3c201ef58    Yesenia  Martinez    Male
4      5  1bA7A3dc874da3c       Lori      Todd    Male

                        Email                   Phone Date of birth  \
0        elijah57@example.net  001-084-906-7849x73518    1945-10-26
1       bethany14@example.com       214.112.6044x4913    1910-03-24
2       bthompson@example.com            277.609.7938    1992-07-02
3   kaitlinkaiser@example.com            584.094.6111    2017-08-03
4  buchananmanuel@example.net       689-207-3558x7233    1938-12-01

            Job Title  Salary
0     Games developer       0
1      Phytotherapist       0
2           Homeopath       0
3   Market researcher       0
4  Veterinary surgeon       0

In [155]:
data['Salary'] = np.where(data['Sex'] == 'Male', 2000, 1000)
data.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Salary
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer,2000
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist,1000
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath,2000
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher,2000
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon,2000

In [156]:
data['Grade'] = np.where(data['Salary'] > 1500, 'A', 'B')
data.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Salary,Grade
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer,2000,A
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist,1000,B
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath,2000,A
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher,2000,A
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon,2000,A

In [157]:
# adding a row
new_row = pd.DataFrame({'index': [1],'User Id': ['123gnkons'], 'First Name': ['Sajid'], 'Last Name': ['Malik'], 'Sex': ['Male'], 'Email': ['jdoe@example.com'], 'Phone': ['123-456-7890'], 'Date of birth': ['2002-01-01'], 'Job Title': ['Software Engineer']})
# Now adding a row need to concat it with the esisiting data
data = pd.concat([data, new_row], ignore_index=True)
data.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Salary,Grade,index
0,1.0,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer,2000.0,A,NaN
1,2.0,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist,1000.0,B,NaN
2,3.0,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath,2000.0,A,NaN
3,4.0,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher,2000.0,A,NaN
4,5.0,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon,2000.0,A,NaN

In [158]:
data.loc['Email':'elijah57@example.net']

Empty DataFrame
Columns: [Index, User Id, First Name, Last Name, Sex, Email, Phone, Date of birth, Job Title, Salary, Grade, index]
Index: []

In [159]:
pd.read_csv("Datasets/people-100.csv")

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

MultiIndex

In [160]:
pd.read_csv("Datasets/people-100.csv")

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [161]:
# Now we apply set_index() method 
multi_index = data.set_index(['First Name', 'Last Name'])
multi_index.head()

,,Index,User Id,Sex,Email,Phone,Date of birth,Job Title,Salary,Grade,index
First Name,Last Name,,,,,,,,,,
Shelby,Terrell,1.0,88F7B33d2bcf9f5,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer,2000.0,A,NaN
Phillip,Summers,2.0,f90cD3E76f1A9b9,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist,1000.0,B,NaN
Kristine,Travis,3.0,DbeAb8CcdfeFC2c,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath,2000.0,A,NaN
Yesenia,Martinez,4.0,A31Bee3c201ef58,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher,2000.0,A,NaN
Lori,Todd,5.0,1bA7A3dc874da3c,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon,2000.0,A,NaN

In [162]:
multi_index.loc[('Phillip', 'Summers')]

Index                              2.0
User Id                f90cD3E76f1A9b9
Sex                             Female
Email            bethany14@example.com
Phone                214.112.6044x4913
Date of birth               1910-03-24
Job Title               Phytotherapist
Salary                          1000.0
Grade                                B
index                              NaN
Name: (Phillip, Summers), dtype: object

In [163]:
import pandas as pd

store_data = {
    'Region':   ['North', 'North', 'North', 'South', 'South', 'South', 'East', 'East'],
    'Category': ['Electronics', 'Electronics', 'Clothing', 'Electronics', 'Clothing', 'Clothing', 'Electronics', 'Clothing'],
    'Product':  ['Laptop', 'Phone', 'T-Shirt', 'Laptop', 'T-Shirt', 'Jeans', 'Phone', 'Jeans'],
    'Sales':    [1200, 800, 150, 1100, 180, 220, 750, 200],
    'Profit':   [240, 160, 45, 220, 54, 66, 150, 60],
    'Qty':      [12, 20, 30, 11, 36, 22, 15, 25]
}

df = pd.DataFrame(store_data)
print(df)

  Region     Category  Product  Sales  Profit  Qty
0  North  Electronics   Laptop   1200     240   12
1  North  Electronics    Phone    800     160   20
2  North     Clothing  T-Shirt    150      45   30
3  South  Electronics   Laptop   1100     220   11
4  South     Clothing  T-Shirt    180      54   36
5  South     Clothing    Jeans    220      66   22
6   East  Electronics    Phone    750     150   15
7   East     Clothing    Jeans    200      60   25

In [164]:
sale = df.set_index(['Region', 'Category'])
sale

                    Product  Sales  Profit  Qty
Region Category
North  Electronics   Laptop   1200     240   12
       Electronics    Phone    800     160   20
       Clothing     T-Shirt    150      45   30
South  Electronics   Laptop   1100     220   11
       Clothing     T-Shirt    180      54   36
       Clothing       Jeans    220      66   22
East   Electronics    Phone    750     150   15
       Clothing       Jeans    200      60   25

In [166]:
sale.loc[('North', 'Clothing')]

C:\Users\LAPTOP GENERATION\AppData\Local\Temp\ipykernel_16660\544955997.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  sale.loc[('North', 'Clothing')]

                 Product  Sales  Profit  Qty
Region Category
North  Clothing  T-Shirt    150      45   30

In [168]:
sales1 = df.set_index(['Region','Category','Product','Sales','Profit','Qty'])
sales1

Empty DataFrame
Columns: []
Index: [(North, Electronics, Laptop, 1200, 240, 12), (North, Electronics, Phone, 800, 160, 20), (North, Clothing, T-Shirt, 150, 45, 30), (South, Electronics, Laptop, 1100, 220, 11), (South, Clothing, T-Shirt, 180, 54, 36), (South, Clothing, Jeans, 220, 66, 22), (East, Electronics, Phone, 750, 150, 15), (East, Clothing, Jeans, 200, 60, 25)]

In [170]:
sales1.loc[('North', 'Electronics', 'Laptop', 1200, 240, 12)]

Series([], Name: (North, Electronics, Laptop, 1200, 240, 12), dtype: float64)